### ISSUE TITLE
Typo in line 45 of 09_Data_Structures_Modern_Operators_and_Strings/03_spread_operator.js

### ISSUE THREAD

**Issue by formidablae** [somekindofwallflower/complete-javascript-course-2021#75]
'Gnocci' should be 'Gnocchi' in line 45 of https://github.com/somekindofwallflower/complete-javascript-course-2021/blob/master/09_Data_Structures_Modern_Operators_and_Strings/03_spread_operator.js

**Comment by somekindofwallflower** [comment]
> 'Gnocci' should be 'Gnocchi' in line 45 of https://github.com/somekindofwallflower/complete-javascript-course-2021/blob/master/09_Data_Structures_Modern_Operators_and_Strings/03_spread_operator.js

"Gnocci" is something I have created in my kitchen and I intend to put it on the menu in order to get feedback from customers :D
